{% set version = '2.4.3' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-neonutilities
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/neonUtilities_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/neonUtilities/neonUtilities_{{ version }}.tar.gz
  sha256: 5e8af39325db9d745ec75813008ab3a95eaefdc2d3289c1261f45dfb557cee4a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r.utils
    - r-curl
    - r-data.table
    - r-downloader
    - r-httr
    - r-jsonlite
    - r-pbapply
    - r-stringr
    - r-tidyr
  run:
    - r-base
    - r-r.utils
    - r-curl
    - r-data.table
    - r-downloader
    - r-httr
    - r-jsonlite
    - r-pbapply
    - r-stringr
    - r-tidyr

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('neonUtilities')"  # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('neonUtilities')\""  # [win]
    # c.f. https://github.com/conda-forge/staged-recipes/pull/30115#issuecomment-2902965608
    # - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://github.com/NEONScience/NEON-utilities
  license: AGPL-3.0-only
  summary: Utilities for Working with NEON Data
  description: |
    NEON data packages can be accessed through the NEON Data Portal <https://www.neonscience.org>
    or through the NEON Data API (see <https://data.neonscience.org/data-api> for documentation).
    Data delivered from the Data Portal are provided as monthly zip files packaged within
    a parent zip file, while individual files can be accessed from the API. This package
    provides tools that aid in discovering, downloading, and reformatting data prior
    to use in analyses. This includes downloading data via the API, merging data tables
    by type, and converting formats. For more information, see the readme file at <https://github.com/NEONScience/NEON-utilities>.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'
  dev_url: https://github.com/NEONScience/NEON-utilities

extra:
  recipe-maintainers:
    - conda-forge/r
    - matthewfeickert
