schema_version: 1

context:
  version: "4.0.2"

package:
  name: r-neonutilities
  version: ${{ version }}

source:
  url:
    - ${{ cran_mirror }}/src/contrib/neonUtilities_${{ version }}.tar.gz
    - ${{ cran_mirror }}/src/contrib/Archive/neonUtilities/neonUtilities_${{ version }}.tar.gz
  sha256: 7cad5f6ee3537ff16be2d8fb4082316919dcc58bb611b654079108abf461d44e

build:
  number: 0
  noarch: generic
  script: ${{ R }} CMD INSTALL --build .

requirements:
  host:
    - r-base
    - r-r.utils
    - r-arrow
    - r-curl
    - r-data.table >=1.17.8
    - r-downloader
    - r-dplyr
    - r-httr
    - r-jose
    - r-jsonlite
    - r-pbapply
    - r-rlang
    - r-tidyr
    - r-duckdbfs
  run:
    - r-base
    - r-r.utils
    - r-arrow
    - r-curl
    - r-data.table >=1.17.8
    - r-downloader
    - r-dplyr
    - r-httr
    - r-jose
    - r-jsonlite
    - r-pbapply
    - r-rlang
    - r-tidyr
    - r-duckdbfs

tests:
  - r:
      libraries:
        - neonUtilities
  - files:
      source:
        - tests/
    requirements:
      run:
        - r-testthat
    script:
      - Rscript -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"

about:
  license: AGPL-3.0-only
  summary: Utilities for Working with NEON Data
  description: |
    NEON data packages can be accessed through the NEON Data Portal <https://www.neonscience.org>
    or through the NEON Data API (see <https://data.neonscience.org/data-api> for documentation).
    Data delivered from the Data Portal are provided as monthly zip files packaged within
    a parent zip file, while individual files can be accessed from the API. This package
    provides tools that aid in discovering, downloading, and reformatting data prior
    to use in analyses. This includes downloading data via the API, merging data tables
    by type, and converting formats. For more information, see the readme file at <https://github.com/NEONScience/NEON-utilities>.
  license_file:
    - ${{ PREFIX }}/lib/R/share/licenses/AGPL-3
  homepage: https://github.com/NEONScience/NEON-utilities
  repository: https://github.com/NEONScience/NEON-utilities

extra:
  recipe-maintainers:
    - conda-forge/r
    - cklunch
    - matthewfeickert
